server:
  port: 3002

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:mysql://localhost:3306/kahust_room
    username: root
    password: hungthoi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
