server:
  port: 3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: quiz-service
            uri: http://quiz-service:3001
            predicates:
              - Path=/quizzes/**
          - id: room-service
            uri: http://room-service:3002
            predicates:
              - Path=/rooms/**
          - id: user-service
            uri: http://user-service:3003
            predicates:
              - Path=/users/**, /auth/**   

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: api-gateway

jwt:
  secret: "this is a very long secret key that is pretty secure"