server:
  port: 3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quizzes/**
            
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**
        
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 
    
jwt:
  secret: "very secret"